<!-- Docs nav ================================================== -->
<div class="row">
    <div class="span12">

        <section id="about">
            <div class="page-header">
              <h2>
                  <?php echo $this->translate('What is a webshost');?>
              </h2>
            </div>

            <div class="row-fluid">
                <p class="lead">
                    Webshot Screen Server it's an web application for generate website  screenshots. System is based on CutyCapt application (<a href="http://cutycapt.sourceforge.net">http://cutycapt.sourceforge.net</a>). It's allows you to take screenshots of any web pages and save them as images in png formats. Application was created in PHP technology and uses Zend Framework whith Doctrine 2.
                </p>
                <p class="lead">
                    To create any web page screenshot you must registered "Service". Every Service has uqniue hash  - identification code, and sign code - key to sign request for take screenshot. Sample use in Zend Framework:
                <pre>
                    public function webshotAction()
                    {
                            $params = array(
                              'url' => 'http://google.pl',
                              'hash' => '2131sada', //unique identifcator of service
                              'sign' => 'adad13123' //sign key for http://google.pl + 2131sada
                            );

                            $url = 'yourdomain/api/create';            
                            $client = new Zend_Http_Client($url);
                            $client->setMethod(Zend_Http_Client::POST)
                                   ->setHeaders('X-Requested-With', 'XMLHttpRequest') 
                                   ->setParameterPost($params)
                                   ->setConfig(array('timeout' => 180));

                            $response = $client->request();

                            $return = Zend_Json::decode($response->getBody());
                            $code = isset($return['code']) ? $return['code'] : 200;

                          if ($code === 200) {
                              $this->_helper->viewRenderer->setNoRender(true);
                              $this->_helper->layout->disableLayout();

                              $content = file_get_contents($return['image']);
                              $this->getResponse()->setHeader('Content-type', 'image/png');
                              $this->getResponse()->setBody($content);
                              $this->getResponse()->sendResponse();  
                            } else {
                              throw new Exception('An error on generate screenshot');
                            }
                        }
                </pre>
                </p>
                <p class="lead">
                    <strong>Avaiable options</strong>: <?php echo implode(',', $this->avaiableOptions) , '.'; ?>
                </p>
                
                <p class="lead">
                    <strong>Github repository</strong>: <a href="https://github.com/lciolecki/webshot">https://github.com/lciolecki/webshot</a>
                </p>
            </div>
        </section>
        
        <section id="create-screen">
            <div class="page-header">
              <h2>
                  <?php echo $this->translate('Create screen');?>
              </h2>
            </div>

            <div class="row-fluid" id="form-container">
                <?php echo $this->form; ?>
            </div>
            
            <div class="loading" style="display: none;" id="loading-container">
                <p class="row-fluid">
                    <img style="height: 50px" src="<?php echo $this->media('/img/loading.gif'); ?>" />
                    Please wait while, we generate screenshot...
                </p>
            </div>
            
            <div id="screenshot-container" style="display: none;">
                <img src="" />
            </div>
            
        </section>
    </div>
</div>

<script type="text/javascript">
$(function(){
    $('#webshot-form').on('submit', function(e){
        e.preventDefault();
        var self = $(this);

        $.ajax({
            type: 'POST',
            url: self.attr('action'),
            data: self.serialize(),
            beforeSend: function() {
                $('#form-container').hide();
                $('#loading-container').show();
            },
            success: function(data, textStatus, jqXHR) {
                console.log('success' , data);
                $('#loading-container').hide();
                $('#screenshot-container img').attr('src', data.image);
                $('#screenshot-container').show();
            },
            error: function(data, textStatus, jqXHR) {
                var response = data.responseJSON;
                $('#loading-container').hide();
                alert('Code: ' + response.code + '. Message: ' + response.message);
                $('#form-container').show();
            }
        });
        
    });
});   
</script>

