<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Files
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Files extends EntityRepository
{
}
