<?php

namespace Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Webshots
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Webshots extends EntityRepository
{
    /**
     * Metoda zwracajaca liczbe utworzonych webshotow danego dnia
     * 
     * @param int $serviceId
     * @param \Zend_Date $date
     * @return int
     */
    public function getCountForDay($serviceId, \DateTime $date)
    {
        $date = clone $date;
        $start = $date->format('Y-m-d');
        $date->modify('+1 day');
        $end = $date->format('y-m-d');
        
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(ws.id) as cnt')
            ->from($this->getEntityName(), 'ws')
            ->where('ws.service = :service')
            ->andWhere('ws.dateCreate >= :start')
            ->andWhere('ws.dateCreate <= :end')
            ->setParameters(array(
                'service' => $serviceId,
                'start' => $start,
                'end' => $end
            ));
        
        return (int) $qb->getQuery()->getSingleScalarResult();
    }
}
